# Requires Feature Preview Improved container support - https://docs.github.com/en/github/getting-started-with-github/exploring-early-access-releases-with-feature-preview
name: Push latest version to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

env:
  TARGET_BASE: build-app
  TARGET_APP: app

# Hardcoded values:
# unfor19/aws-sdk-cpp-examples

jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/aws-sdk-cpp-examples:latest"
            DOCKERFILE_PATH: Dockerfile
            BASE_IMAGE: ubuntu:20.04
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/aws-sdk-cpp-examples:latest-alpine"
            DOCKERFILE_PATH: Dockerfile.alpine
            BASE_IMAGE: alpine:3.12
    steps:
      - uses: actions/checkout@v2
      - name: docker login ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: docker pull cached
        run: |
          docker pull "${{ matrix.BASE_IMAGE }}"
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}" || true
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}" || true
      - name: docker build cached
        run: |
          docker build . -t "cached-${TARGET_BASE}" --cache-from="${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}" -f "${{ matrix.DOCKERFILE_PATH }}" --target "${TAGET_BASE}"
          docker build . -t "cached-${TARGET_APP}"  --cache-from="${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"  -f "${{ matrix.DOCKERFILE_PATH }}" --target "${TARGET_APP}"
      - name: docker tag cached
        run: |
          docker tag "cached-${TARGET_BASE}" "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}"
          docker tag "cached-${TARGET_APP}"  "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"
      - name: docker push cached to ghcr
        run: |
          docker push "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}"
          docker push "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"

  dockerhub-push:
    needs: docker-build
    name: push latest
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/aws-sdk-cpp-examples:latest"
            DOCKERFILE_PATH: Dockerfile
            DOCKERHUB_TAG: "unfor19/aws-sdk-cpp-examples:latest"
            BASE_IMAGE: ubuntu:20.04
          - GHCR_CACHED_TAG_PREFIX: "ghcr.io/unfor19/aws-sdk-cpp-examples:latest-alpine"
            DOCKERFILE_PATH: Dockerfile.alpine
            DOCKERHUB_TAG: "unfor19/aws-sdk-cpp-examples:latest-alpine"
            BASE_IMAGE: alpine:3.12
    steps:
      - uses: actions/checkout@v2
      - name: docker pull cached from ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull "${{ matrix.BASE_IMAGE }}"
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_BASE}"
          docker pull "${{ matrix.GHCR_CACHED_TAG_PREFIX }}-${TARGET_APP}"
      - name: docker build image
        run: |
          docker build . -t "${{ matrix.DOCKERHUB_TAG }}" -f "${{ matrix.DOCKERFILE_PATH }}" --target "${TARGET_APP}"
      - name: docker push to dockerhub
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${{ matrix.DOCKERHUB_TAG }}"
