name: Push latest version to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"

jobs:
  docker_build_ubuntu:
    runs-on: ubuntu-20.04
    name: docker build ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set env vars
        run: |
          export BRANCH_NAME=${{ env.GITHUB_REF_SLUG }}
          [[ $BRANCH_NAME = "master" ]] && export BRANCH_NAME=master-test
          echo DOCKER_TAG=docker.pkg.github.com/${GITHUB_REPOSITORY}/${BRANCH_NAME//\//-}:test >> $GITHUB_ENV
      - name: docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: docker pull
        run: |
          docker pull "$DOCKER_TAG" || true
      - name: docker build
        run: docker build . -t cached --cache-from="$DOCKER_TAG" -f Dockerfile
      - name: docker tag
        run: docker tag cached "$DOCKER_TAG"
      - name: docker push
        run: docker push "$DOCKER_TAG" || true

  docker_build_alpine:
    runs-on: ubuntu-20.04
    name: docker build alpine
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set env vars
        run: |
          export BRANCH_NAME=${{ env.GITHUB_REF_SLUG }}
          [[ $BRANCH_NAME = "master" ]] && export BRANCH_NAME=master-test
          echo DOCKER_TAG=docker.pkg.github.com/${GITHUB_REPOSITORY}/${BRANCH_NAME//\//-}:test >> $GITHUB_ENV
      - name: docker login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: docker pull
        run: |
          docker pull "$DOCKER_TAG" || true
      - name: docker build
        run: docker build . -t cached --cache-from="$DOCKER_TAG" -f Dockerfile.alpine
      - name: docker tag
        run: docker tag cached "$DOCKER_TAG"
      - name: docker push
        run: docker push "$DOCKER_TAG" || true

  dockerhub-latest:
    name: push latest ubuntu
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: unfor19/aws-sdk-cpp:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile --tag "${DOCKER_TAG}"
      - name: Push to DockerHub
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}" && echo "Pushed $DOCKER_TAG"

  dockerhub-latest-alpine:
    name: push latest alpine
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: unfor19/aws-sdk-cpp:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build . --file Dockerfile.alpine --tag "${DOCKER_TAG}"
      - name: Push to DockerHub
        run: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "${DOCKER_TAG}" && echo "Pushed $DOCKER_TAG"
